name: IOSBUILDLane

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
 IOS_RUN:
      runs-on: macos-latest
      steps: 
      - uses: actions/checkout@v2
      - name: Create IPA Build
        run: cd ios & fastlane beta
      
      - name: Upload IPA
        uses: actions/upload-artifact@v1
        with:
          name: sample.ipa
          path: fastlane/builds/
