
name: IOSBUILD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ initial_appcentre ]
  pull_request:
    branches: [ initial_appcentre ]
jobs:
 IOS_RUN:
      runs-on: self-hosted
      steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Install pod dependencies
        run: |
          cd ios && npx pod-install
      - name: Build ios app
        run: |       
          cd ios && xcodebuild -workspace MyReactNative.xcworkspace -scheme MyReactNative archive -archivePath MyReactNative.xcarchive -allowProvisioningUpdates
          xcodebuild -exportArchive -archivePath ./MyReactNative.xcarchive -exportPath ./build -exportOptionsPlist MyReactNative/Info.plist
      - name: Deploy to App Center
        run: |
          npm install appcenter-cli@2.3.3
          npx appcenter distribute release --token "${{secrets.APP_CENTER_IOS_API_TOKEN}}" --app "kishorerajasekar/testnative-1" --group "test" --file "ios/build/MyReactNative.ipa"
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: myapp.ipa
          path: ios/build/
