
name: Unit Test/CI-CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  create:
    tags:
jobs:
 Android_Relese:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Unit Test
        if: ${{ failure() || success() }}
        run: |
          npm run-script test
     
      - name: Upload Artifact
        if: ${{ failure() || success() }}
        uses: actions/upload-artifact@v1
        with:
          name: unit_test_result
          path: coverage/lcov-report
